title: The Global Pandemic 
author: Chandramani
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Here we are going to talk about the pandemic which took the whole world by a major loss to the human kind as well as there living.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme:minima
